repos:
# Python hooks
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
     - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
     - id: isort
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.15.0
    hooks:
     - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
     - id: mypy
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v5.0.4
    hooks:
     - id: flake8

# Javascript hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.0
    hooks:
     - id: eslint
       files: \.js$
